### ISSUE TITLE
Crash on Observer

### ISSUE THREAD

**Issue by rohit-aq** [josejuanqm/VersaPlayer#29]
[
![Crash](https://user-images.githubusercontent.com/38911858/54580951-697a0200-4a30-11e9-8544-5f4b1d991d2d.png)
](url)

You can easily reproduce if you quickly show/close the player. For now, I am adding guard for self object but please fix it in the next version.

**Comment by O-mkar** [comment]
Same issue, @rohit-aq do you have a temp solution you can share?

**Comment by rohit-aq** [comment]
The root cause of this issue is, the handler is deallocated before the observer was removed. I tried putting a guard condition but that doesn't help as the library gets updated every time pod is updated. I am still facing the issue.

**Comment by rohit-aq** [comment]
If you are adding VersaPlayerView using Storyboard then remove it from Storyboard and add it using the code, it won't crash.

**Comment by O-mkar** [comment]
Thanks, Mate let me see if it helps.

**Comment by josejuanqm** [comment]
Thank you, I'll work on this today

**Comment by josejuanqm** [comment]
Should be fixed in 2.3.3, please re-open if needed.

**Comment by RajChanchal** [comment]
It still crashes, despite updating to version 3.0.0.

![Screen Shot 2019-07-16 at 5 52 56 PM](https://user-images.githubusercontent.com/7058465/61300499-1e5fd800-a7f3-11e9-8cab-a54553812b9d.png)

As you can see in the above screenshot the 'handler' is nil

**Comment by Eratos1122** [comment]
![Screen Shot 2020-07-03 at 11 42 23 AM](https://user-images.githubusercontent.com/37297413/86483553-4907b100-bd22-11ea-8af8-1bbb54351032.png)
It is crashed when a new video player is opened

**Comment by Eratos1122** [comment]
> If you are adding VersaPlayerView using Storyboard then remove it from Storyboard and add it using the code, it won't crash.

Still crash

**Comment by Eratos1122** [comment]
I fixed it by using the updated one

`pod 'VersaPlayer', :git => 'https://github.com/mobile-davinder/VersaPlayer.git'`

It would be helpful for you 🙏
